### ISSUE TITLE
npm run start 报错

### ISSUE THREAD

**Issue by WilliamCheen** [bytemate/chatapi-single#24]
Starting chatgpt failed, retrying...
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/chatapi-single/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (/home/chatapi-single/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by myfingerhurt** [comment]
#19
