### ISSUE TITLE
容器内curl发生异常

### ISSUE THREAD

**Issue by an9xyz** [bytemate/chatapi-single#25]
```bash
# curl -X "POST" "http://localhost:4000/message"     -H 'Content-Type: application/json; charset=utf-8'   -d $'{  "message": "Hello"}'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token &#39;<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/types/json.js:160:10)<br> &nbsp; &nbsp;at parse (/app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:204:9)<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:231:16)<br> &nbsp; &nbsp;at done (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:512:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12), &quot;#&quot; is not valid JSON<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (/app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/types/json.js:160:10)<br> &nbsp; &nbsp;at parse (/app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /app/node_modules/.store/body-parser@1.20.1/node_modules/body-parser/lib/read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:204:9)<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:231:16)<br> &nbsp; &nbsp;at done (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:220:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/.store/raw-body@2.5.1/node_modules/raw-body/index.js:280:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:512:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12)</pre>
</body>
</html>
```

部署成功后，启动验证发生以上异常

**Comment by fuergaosi233** [comment]
这个命令是直接复制粘贴的么？

**Comment by an9xyz** [comment]
是的，昨天本地测试好使，补充运行成功日志
```
All migrations have been successfully applied.
Starting chatgpt with config: {
  "email": "******",
  "password": "*******",
  "sessionToken": "",
  "reverseProxyUrl": "https://chat.y1s1.host",
  "isProAccount": false,
  "markdown": false,
  "debug": false,
  "isGoogleLogin": false,
  "isMicrosoftLogin": false,
  "minimize": false,
  "proxyServer": "x*****t:7890"
}
🎉 Started chatgpt success!
🚀 Server ready at: http://localhost:4000/
```

**Comment by yanshibin** [comment]
好像是GG了

**Comment by an9xyz** [comment]
找到原因了，因为curl单行执行参数json解析失败，把多余的空格删掉就好了
 **-d $'{  "message": "Hello"}'**
