### ISSUE TITLE
google login error

### ISSUE THREAD

**Issue by jb522185660** [bytemate/chatapi-single#30]
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:../data/data.db"

2 migrations found in prisma/migrations

No pending migrations to apply.
Starting chatgpt with config: {
  "email": "xxx@xxx.com",
  "password": "xxx",
  "sessionToken": "",
  "reverseProxyUrl": "https://chat.y1s1.host",
  "isProAccount": false,
  "markdown": true,
  "debug": false,
  "isGoogleLogin": true,
  "isMicrosoftLogin": false,
  "minimize": false
}
Starting chatgpt failed, retrying...
ProtocolError: Waiting for selector `input[type="email"]` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise ()
    at CDPSessionImpl.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:98:68)
Starting chatgpt failed, retrying...
ProtocolError: Waiting for selector `input[type="email"]` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise ()
    at CDPSessionImpl.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:98:68)
Starting chatgpt failed, retrying...
ProtocolError: Waiting for selector `input[type="email"]` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise ()
    at CDPSessionImpl.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:98:68)
Starting chatgpt failed, retrying...
ProtocolError: Waiting for selector `input[type="email"]` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise ()
    at CDPSessionImpl.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:98:68)
Starting chatgpt failed, retrying...
ProtocolError: Waiting for selector `input[type="email"]` failed: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise ()
    at CDPSessionImpl.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WaitTask.rerun (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:98:68)

**Comment by fuergaosi233** [comment]
Attempt to turn off Multi-factor authentication🤔
